dont-use-soft-clips actually works in Mutect2
broadinstitute/gatk pull request #6823
Opened 2020-09-15 19:28 UTC by davidbenjamin

Closes #6686

@fleharty This option did nothing because a copy of the original reads was modified.  By deleting the unnecessary mapping quality filtering (this is totally redundant with the M2 read filter), we finalize (and thereby discard soft clips if requested) an assembly region made from the original reads, not a copy.

2020-09-15 20:02 UTC, droazen commented
@davidbenjamin What's the state of this argument for the `HaplotypeCaller`?

2020-09-16 00:27 UTC, davidbenjamin commented
@droazen It already works for HaplotypeCaller.

2020-10-08 03:12 UTC, davidbenjamin commented
@fleharty Can we get this in for Friday's release?

2020-10-08 18:43 UTC, fleharty requested changes
@davidbenjamin Looks almost ready, but could we be a bit stricter on the test?

2020-10-08 18:43 UTC, fleharty commented on src/test/java/org/broadinstitute/hellbender/tools/walkers/mutect/Mutect2IntegrationTest.java
> +        Assert.assertTrue(indelsWithoutSoftClips.size() < indelsWithSoftClips.size());
Can we be more specific about which variants are called/not called when the option is set/unset?
I'd hate for this to pass by chance, which is almost has a 50/50 chance of, even if it's not doing what we expect.

2020-10-08 18:44 UTC, fleharty commented
@davidbenjamin back to you

2020-10-22 18:55 UTC, fleharty commented
@davidbenjamin Do you have a moment to push this along?

2020-10-23 14:40 UTC, davidbenjamin commented
I will try to finish this today.

2020-10-23 14:51 UTC, davidbenjamin commented
@fleharty back to you

2020-10-23 20:39 UTC, fleharty approved these changes
Looks good!  Merge away!

2020-10-25 15:40 UTC, merged