gCNV restarts inference with a new random seed in case ELBO converges to a NaN (do NOT merge)
broadinstitute/gatk pull request #6866
Opened 2020-10-06 21:58 UTC by asmirnov239

This is intended to alleviate transient issues with GermlineCNVCaller inference in which the ELBO converges to a NaN value, by calling the python gCNV code with an updated random seed input.

2020-10-07 14:30 UTC, cmnbroad requested changes

2020-10-29 22:23 UTC, asmirnov239 commented
@cmnbroad I added the changes you suggested, could you take a look? 

I added a set of methods to `PythonScriptExecutor` mirroring existing ones that return booleans.  I tried to extract as much common code as possible. Also, because now the entry point in  `ScriptExecutor` that return `ProcessOutput` does not process and throw any exceptions, I extracted that processing code and manually call it from `GermlineCNVCaller`. Let me know if you have a better idea on a better way to handle it.

If that looks good to you, could you also suggest what unit tests you would like me to add?

2020-11-04 16:13 UTC, cmnbroad requested changes
@asmirnov239 Thanks for the update. There are a bunch of minor/cosmetic comments, and one request for a minor refactoring change, but overall this looks pretty good.

As for tests, I think there are 4 `PythonScriptExecutorUnit` test cases:

- Two cases for `executeScriptAndGetOutput(final Resource scriptResource,..), one that executes a script that just does `exit 239`, and one that is some simple code that just succeeds without setting an explicit exit code, with both calling and validating the `ProcessOutput` exitcode, and the return value from getExceptionMessageFromScriptError`.
- The same two cases, only for `executeArgsAndGetOutput`.

Ideally there would also be a negative case for GermlineCNVCaller if you can force it to fail to converge, but maybe thats harder.

2020-12-07 22:58 UTC, asmirnov239 commented on src/main/java/org/broadinstitute/hellbender/tools/copynumber/GermlineCNVCaller.java
> +                logger.info("The inference ran into a NaN error and will be restarted one more time.");
Yes that's better I agree. Done

2020-12-07 23:03 UTC, asmirnov239 commented on src/main/java/org/broadinstitute/hellbender/utils/python/PythonScriptExecutor.java
> +     * @param scriptArgs args to be passed to the python codescriptArgs
Oops, this was an accident

2020-12-07 23:31 UTC, asmirnov239 commented on src/main/resources/org/broadinstitute/hellbender/tools/copynumber/case_denoising_calling.py
> +        sys.exit(239) # Pass an exit code to Java side indicating restart is needed
Definitely. I added it to gcnvkernel.io_const and kept it lower case to stick with the convention there

2020-12-07 23:46 UTC, asmirnov239 commented on src/main/java/org/broadinstitute/hellbender/tools/copynumber/GermlineCNVCaller.java
Done!

2020-12-09 00:26 UTC, asmirnov239 commented on src/main/java/org/broadinstitute/hellbender/utils/runtime/ScriptExecutor.java
> +    public String getExceptionMessageFromScriptError(final ProcessOutput po) {
I like that. Done!

2020-12-17 18:58 UTC, asmirnov239 commented
@cmnbroad I addressed your comments, except for making a negative test case for GermlineCNVCaller - I added that to  #6893 issue with an ongoing list of needed tests. Let me know if the changes look good to you.

2021-01-11 19:14 UTC, cmnbroad approved these changes
@asmirnov239 This looks pretty good now - only one minor comment. I'm not sure if this has already had a merge test run with the changes in https://github.com/broadinstitute/gatk/pull/6554, so it might be worth rebasing and running the tests one more time before merge.

2021-01-11 19:14 UTC, cmnbroad commented on src/main/java/org/broadinstitute/hellbender/utils/python/PythonScriptExecutor.java
> +    private List<String> validateAndBuildCommand(final String scriptName, final List<String> pythonProcessArgs, final List<String> scriptArgs) {
This method can be static.

2021-01-12 18:18 UTC, merged