Added requster pays option to germline and somatic CNV WDLs
broadinstitute/gatk pull request #6870
Opened 2020-10-08 00:36 UTC by asmirnov239

@mwalker174 Could you please review? 

I only added `gcs_project_for_requester_pays` input to tasks that need access to BAMs. Do we also need it for the ones that require reference such as `PreprocessIntervals`?

2020-10-08 16:04 UTC, mwalker174 requested changes
Thanks @asmirnov239, just a few corrections here.

2020-10-08 16:04 UTC, mwalker174 commented on scripts/cnv_wdl/somatic/cnv_somatic_panel_workflow.wdl
> +      String? gcs_project_for_requester_pays
Add this to `CollectCounts` input

2020-10-09 15:09 UTC, ldgauthier commented
@mwalker174 Since Andrey is out, I addressed your comments and I think I caught a couple more missing inputs.

2020-10-09 17:24 UTC, mwalker174 approved these changes
Looks good to me!

2020-10-09 18:46 UTC, merged