Created a debug output mode that dumps the the exact inputs/outputs of the PairHMM to a file
broadinstitute/gatk pull request #7660
Opened 2022-02-02 21:26 UTC by jamesemery

Resolves #7647

2022-02-07 17:42 UTC, jamesemery commented
@droazen could you take a look at this branch?

2022-03-09 20:03 UTC, droazen requested changes
@jamesemery Back to you with a couple of quick comments. Main question is why the AVX_LOGLESS_CACHING test case is disabled

2022-03-09 20:03 UTC, droazen commented on src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/HaplotypeCallerIntegrationTest.java
> +                //{PairHMM.Implementation.AVX_LOGLESS_CACHING, new File(TEST_FILES_DIR, "expected.AVX.hmmresults.txt")}, //TODO disabled because of failures on travis
Can you elaborate on why this is disabled? Ideally we want test coverage for the default HMM in GATK...

2022-03-09 20:25 UTC, jamesemery commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/LikelihoodEngineArgumentCollection.java
> +    @Argument(fullName="pair-hmm-results-file", doc="File to write exact pairHMM inputs/outputs to for debugging purposes", optional = true)
all of them as far as i've tested. I have a test for all of them but the AVX was producing some different output on travis...

2022-03-09 20:25 UTC, jamesemery commented on src/main/java/org/broadinstitute/hellbender/utils/pairhmm/PairHMM.java
> +                writeToResultsFileIfApplicable(readBases, readQuals, readInsQuals, readDelQuals, overallGCP, alleleBases, lk);
yes i have tests for both.

2022-03-09 20:29 UTC, jamesemery commented on src/main/java/org/broadinstitute/hellbender/utils/pairhmm/PairHMM.java
> +                debugOutputStream.write("\n" + new String(alleleBases) + " " + new String(readBases) + " " + SAMUtils.phredToFastq(readQuals) + " " + SAMUtils.phredToFastq(readInsQuals) + " " + SAMUt
I don't think so. If the alleles or the phred to fastq mehtods are returning results with whitespaces in them we have much bigger problems...

2022-03-09 20:31 UTC, jamesemery commented on src/main/java/org/broadinstitute/hellbender/utils/pairhmm/PairHMM.java
> +            logger.info("Total compute time in PairHMM computeLogLikelihoods() : " + (pairHMMComputeTime * 1e-9));
seconds I believe just as it has in the past for gatk. Its using nanoTime so converting to seconds should be 10^-9.

2022-03-10 15:34 UTC, jamesemery commented
@droazen I loosened the failing test and responded to your comments? Anything else before we can get this in?

2022-03-10 17:25 UTC, droazen approved these changes
👍

2022-03-10 17:27 UTC, merged