365 vat clinvar updates
broadinstitute/gatk pull request #7756
Opened 2022-04-05 20:52 UTC by RoriCremer

2022-04-29 15:58 UTC, rsasch requested changes
I tried running ./build_docker.sh and it failed with the following error:
```
ImportError: Failed to import test module: create_variant_annotation_table_test
Traceback (most recent call last):
  File "/opt/miniconda3/envs/gvs/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/rasch/p/gatk/scripts/variantstore/wdl/extract/create_variant_annotation_table_test.py", line 13, in <module>
    from create_variant_annotation_table import make_annotated_json_row
  File "/Users/rasch/p/gatk/scripts/variantstore/wdl/extract/create_variant_annotation_table.py", line 8, in <module>
    import ijson
ModuleNotFoundError: No module named 'ijson'
```

2022-04-29 16:02 UTC, RoriCremer commented on scripts/variantstore/wdl/GvsCreateVATFromAnnotations.wdl
> +            }
I think it's just copy pasta? from a rebase annoyingly

2022-04-29 16:04 UTC, RoriCremer commented
oooh, re: ijson, should I just add checking for and installing it into the ./build_docker.sh file?

I've had it forever since I need it to run the python script. It's in requirements.txt, where else should I put it?

2022-04-29 16:13 UTC, rsasch commented
I think it would be good for there to be as little lift as possible required to run the tests, so adding it to ./build_docker.sh is probably best.

2022-05-03 12:01 UTC, mcovarr requested changes
a couple of Python nitpicks, otherwise looks good

2022-05-03 16:41 UTC, RoriCremer commented
Bec's change resolved!

2022-05-03 16:41 UTC, merged