Vs 262 partial loading independent
broadinstitute/gatk pull request #7843
Opened 2022-05-10 15:47 UTC by mcovarr

Makes CreateVariantIngestFiles robust to partially or fully loaded samples.

Commit 0922ef69f984cc9926326812036988797abc885e is what I actually propose to merge, while commit 80285fe3732b1787492cc4fbbe65518f03916904 randomly injects failures covering all the known failure modes. I tested these changes using both commits and was able to verify that partially loaded samples were handled correctly on subsequent attempts to load the sample (unfortunately we can't actually prevent these partial loadings from happening in the first place because preemptions, among other possible reasons).

2022-05-11 17:05 UTC, gbggrant commented on src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/CreateVariantIngestFiles.java
> +            if (mod == 0) {
Sorry - didn't realize that this was in a commit that was intended for testing purposes only. clever!

2022-05-11 17:33 UTC, mcovarr commented on src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/RefCreator.java
> +    public static boolean doRowsExistFor(CommonCode.OutputType outputType, String projectId, String datasetName, String tableNumber, String sampleId) {
I did test this manually in [this run](https://job-manager.dsde-prod.broadinstitute.org/jobs/c48a2f26-2222-45f1-a15e-41d6400c2537) where shards 2 and 3 exercised all of the injected failure conditions on their failed attempts, during which they would have called this code. There are some BQ "unit tests" in `BigQueryUtilsUnitTest` but I'm not sure how to create an automated test for these conditions.

2022-05-11 17:33 UTC, mcovarr commented on src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/RefCreator.java
> -    public List<List<String>> createRows(final long start, final long end, final VariantContext variant, final String sampleId) {
drive by deletion of code IntelliJ flagged as unused

2022-05-11 17:44 UTC, kcibul commented on src/main/java/org/broadinstitute/hellbender/tools/gvs/ingest/CreateVariantIngestFiles.java
>              } else if (state == LoadStatus.LoadState.PARTIAL) {
Do you want this to be PARTIAL || NONE?  What happens if we've never attempted to load this sample before (which is the most common case by far)

2022-05-11 17:49 UTC, kcibul requested changes
one style/clarity thing, and one major question about Load Status

2022-05-13 15:03 UTC, kcibul approved these changes
Looks great -- assuming the testing code will be removed (ie the mod stuff)

2022-05-13 17:25 UTC, merged