fix tabix index generation
broadinstitute/gatk pull request #7858
Opened 2022-05-18 18:09 UTC by tedsharpe

2022-05-18 18:11 UTC, tedsharpe commented
crude, but effective

2022-06-03 16:09 UTC, mwalker174 requested changes
Nice work here. I think the index dump tool could be quite useful / educational for some users, but it will need at least an integration test.

Also, a regression test for the bug fix would be ideal.

@droazen any comments on engine class changes or the tool?

2022-06-03 16:09 UTC, mwalker174 commented on src/main/java/org/broadinstitute/hellbender/utils/io/FeatureOutputStream.java
> +            final BlockCompressedOutputStream bcos =
For posterity, can you add a comment explaining the necessity for `BlockCompressedOutputStream` instead of `PositionalOutputStream`?

2022-06-03 16:09 UTC, mwalker174 commented on src/main/java/org/broadinstitute/hellbender/tools/DumpTabixIndex.java
> +            System.out.println("#tigs\tformat\tseqCol\tbegCol\tendCol\tmetaChr\tskip");
Preferable to have an output file argument instead of using stdout

2022-06-03 16:09 UTC, mwalker174 commented on src/main/java/org/broadinstitute/hellbender/tools/DumpTabixIndex.java
> +        try ( final InputStream is = new GZIPInputStream(new FileInputStream(tabixIndexFile)) ) {
Add a check that file has extension `FileExtensions.TABIX_INDEX`

2022-06-03 16:09 UTC, mwalker174 commented on src/main/java/org/broadinstitute/hellbender/tools/DumpTabixIndex.java
> +@CommandLineProgramProperties(
Add a docstring with explanation and usage, and annotate as a Barclay `@DocumentedFeature`

2022-06-03 16:09 UTC, mwalker174 commented on src/main/java/org/broadinstitute/hellbender/tools/DumpTabixIndex.java
> +    String tabixIndexFile;
```suggestion
    GATKPath tabixIndexFile;
```

2022-06-06 19:52 UTC, droazen commented
@tedsharpe Any chance this might resolve the issue reported in https://github.com/broadinstitute/gatk/issues/7838, or is that likely unrelated?

2022-06-06 20:13 UTC, tedsharpe commented
@droazen I believe it's unrelated.

2022-06-07 16:29 UTC, tedsharpe commented
I believe the review comments are all addressed, and that this is ready to go.  (Assuming checks all pass.)

2022-06-07 16:45 UTC, mwalker174 approved these changes

2022-06-07 19:02 UTC, merged