Rc vs 63 vat sop documentation
broadinstitute/gatk pull request #7879
Opened 2022-06-01 14:33 UTC by RoriCremer

2022-06-06 18:08 UTC, rsasch requested changes
Unfortunately have to leave these notes here, since the text in question isn't part of the PR diff; apologies if my meaning isn't clear.

> They are cleaned up after 24 hours, but this code needs to be tweaked so that you can’t get into a state where duplicates are created here. The real question here is going to be, is there a use case that we might want to run where adding to a VAT that was created say weeks ago is beneficial, but given that calculations occur on a sample summing level, this seems unlikely.

Do we still need this?  Seems like it belongs in a ticket (or two) and not documentation.

> To check that all of the shards have successfully made it past the first of the sub workflow steps (the most complicated and likely to fail) they will need to be annotated / transformed into json files and put here: gsutil ls [output_path]/annotations/ | wc -l

This (mostly "they will need to be annotated / transformed into json files and put here") makes it sound like the person running the WDL needs to do something else, instead of this being a way to check on the success of the WDL.

Lastly, is the TSV file the only deliverable?  Is there anything else that needs to be communicated...etc.?  Either way, can this be explicitly added to this doc?

2022-06-06 18:08 UTC, rsasch commented on scripts/variantstore/variant_annotations_table/README.md
> +All dropped variants are tracked
Can you add a bit more detail as to how they are tracked?

2022-06-06 18:08 UTC, rsasch commented on scripts/variantstore/wdl/GvsCreateVATAnnotations.wdl
> +        ## note that normalization may create sites with more than 50 alt alleles
Seems like this comment should be up a couple of lines?

2022-06-07 13:49 UTC, gbggrant approved these changes

2022-06-08 20:18 UTC, rsasch requested changes
Sorry to harp on this.  I think you should change
> The pipeline takes in a jointVCF and outputs a table in BigQuery.

to something like

> The pipeline takes in jointVCFs (and index files), creates a table in BigQuery, and outputs a bgzipped TSV file containing the contents of that table, which is the only deliverable.

to make it clear what the final "thing" is that is created and delivered to the client/user.

2022-06-10 16:20 UTC, rsasch approved these changes
looks good 👍🏻

2022-06-10 18:09 UTC, merged