CondenseDepthEvidence tool
broadinstitute/gatk pull request #7926
Opened 2022-06-29 20:42 UTC by tedsharpe

2022-07-05 16:41 UTC, mwalker174 requested changes
Thank you @tedsharpe, the succinctness of this is nice to see and shows how much it pays off to have proper libraries for the sv evidence types. I compared output against the old CondenseReadCounts tool and results seem nearly identical. The only exception being that your tools includes partial bins. 

This is generally better, but there may be some cases where this causes numerical issues with gCNV, such as having extremely small bins. To allow us to move in baby steps, can you also add a `--min-interval-size` parameter, default to 0, and just drop bins below this value. Maybe validate that the given min <= max as well.

Can you also incorporate that into the testing? It appears the test file doesn't have any "partial" bins, but I think that's important behavior to check for.

2022-07-05 17:55 UTC, tedsharpe commented
Positive test demonstrates that the last row, which has nothing to be merged with, gets dropped when minimum interval length is 101 since its length is 100.  (That's why the final row in merged.rd.txt is omitted in this commit.)
I believe all your comments have been addressed.

2022-07-05 17:57 UTC, tedsharpe commented
Oh, wait.  Missed the addToArrayInPlace suggestion.

2022-07-06 15:22 UTC, mwalker174 approved these changes

2022-07-06 18:22 UTC, merged