A few last doc changes
broadinstitute/gatk pull request #7927
Opened 2022-07-01 15:36 UTC by RoriCremer

adding time and cost estimates to the documentation

2022-07-21 19:54 UTC, gbggrant requested changes

2022-07-21 19:54 UTC, gbggrant commented on scripts/variantstore/beta_docs/run-your-own-samples.md
> +| 5000              | 12:00                | $54.00     | $215.06       | $269.06    | $0.05                       |
Double row for 5000 samples!

2022-07-21 20:07 UTC, kayleemathews commented on scripts/variantstore/beta_docs/run-your-own-samples.md
> +| 5000              | 12:00                | $54.00     | $215.06       | $269.06    | $0.05                       |
Good catch!

2022-07-21 20:13 UTC, gbggrant approved these changes

2022-07-22 19:00 UTC, mcovarr approved these changes

2022-07-25 16:22 UTC, merged

2022-07-26 21:09 UTC, kbergin commented on scripts/variantstore/beta_docs/gvs-overview.md
> +| [GvsJointVariantCalling](https://github.com/broadinstitute/gatk/blob/ah_var_store/scripts/variantstore/wdl/GvsJointVariantCalling.wdl) | June, 2022 | [Kaylee Mathews](mailto:kmathews@broadinstitute
Didn't we want this pinned to a particular release so that it doesn't change out from under users?

2022-07-26 21:10 UTC, kbergin commented on scripts/variantstore/beta_docs/gvs-quickstart.md
> +| 10                | 04:30                | $0.84      | $0.51         | $1.35      | $0.14                       |
I thought we had run this on other sets that were larger than this to provide more cost information?

2022-07-26 21:10 UTC, kbergin commented on scripts/variantstore/beta_docs/gvs-quickstart.md
> +| 10                | 04:30                | $0.84      | $0.51         | $1.35      | $0.14                       |
Ah I see those are in a different document and this is just for the quickstart. Nvm!