GL-548 - Update CreateVat code to handle samples that do not contain all population groups.
broadinstitute/gatk pull request #7965
Opened 2022-07-28 18:35 UTC by gbggrant

Update GvsCreateVAT.wdl to build the subpopulation-specific files from the input ancestry file.
Have GvsCreateVAT.wdl only pull fields from the VCF for the selected subpopulations.
Update create_variant_annotation_table.py to set empty population-specific AC/AN/AF, etc. values if population is not present.

2022-07-28 18:38 UTC, gbggrant commented
CreateVAT workflow run on a quickstart with only two populations for the ten samples (amr, afr) [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/30527ce2-3705-4927-a1dc-512468a94a02).

2022-08-01 16:28 UTC, rsasch requested changes
Just one request: please update all the WDLs that use our custom docker image to use the most up-to-date one, "us.gcr.io/broad-dsde-methods/variantstore:gg_vattest_2022_07_28"

2022-08-01 18:01 UTC, gbggrant commented
Sounds good - was thinking of doing that at the last moment (i.e. having the PR approved, build a 'ah_varstore_<date>' docker off of this PR and then update the wdls and then merge.

2022-08-01 18:03 UTC, rsasch approved these changes

2022-08-01 18:13 UTC, RoriCremer commented on scripts/variantstore/wdl/GvsCreateVAT.wdl
nice!

2022-08-01 18:15 UTC, RoriCremer approved these changes

2022-08-02 02:08 UTC, merged