add initial notebook copy pasta
broadinstitute/gatk pull request #8008
Opened 2022-09-01 03:33 UTC by RoriCremer

2022-09-01 15:18 UTC, mcovarr requested changes

2022-09-01 18:31 UTC, RoriCremer commented on scripts/variantstore/wdl/extract/generate_hail_gvs_import.py
> +filtered_vds = hl.vds.VariantDataset(filtered_vds.reference_data, filtered_vd)
I liked the logic of it there, but you are right that it's overkill

2022-09-01 18:46 UTC, mcovarr commented on scripts/variantstore/wdl/extract/generate_hail_gvs_import.py
> +filtered_vd = filtered_vd.annotate_entries(GT=hl.or_missing(hl.coalesce(filtered_vd.FT, True), filtered_vd.GT))
yeah I need to reverse the logic in my brain for how this works in Hail; work in progress... 🙂

2022-09-06 17:42 UTC, mcovarr approved these changes

2022-09-08 17:10 UTC, RoriCremer commented on scripts/variantstore/wdl/extract/generate_hail_gvs_import.py
> +filtered_vd = filtered_vd.annotate_entries(GT=hl.or_missing(hl.coalesce(filtered_vd.FT, True), filtered_vd.GT))
I just keep reciting "filter false is filter fail"

2022-09-16 14:42 UTC, merged