Callset statistics [VS-560]
broadinstitute/gatk pull request #8018
Opened 2022-09-14 12:14 UTC by mcovarr

Successful Quickstart run [here](https://job-manager.dsde-prod.broadinstitute.org/jobs/89b6dda3-42a2-4246-88bd-8b6aa9dd87b7), has not yet been run on larger datasets.

2022-09-14 21:15 UTC, gbggrant reviewed
Where do the outputs go? I don't see anything in the ~{extract_prefix}_statistics table that got created in my [test run](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/GVS%20AoU%20WGS%2010K%20Callset/job_history/889f5c2e-cbb7-482c-a49a-d923aebd8207). 

Also, I kind of think a text file as output would be very useful for analysis/reporting.

2022-09-19 15:48 UTC, RoriCremer commented on scripts/variantstore/wdl/GvsCallsetStatistics.wdl
> +        # Schemas extracted programatically: https://stackoverflow.com/a/66987934
cool!

2022-09-19 16:00 UTC, RoriCremer commented on scripts/variantstore/wdl/GvsCallsetStatistics.wdl
> +        SELECT "~{filter_set_name}" filter_set_name,
I know that none of the explanations are in the code that you are looking at to write this wdl, but I think getting Lee to add some context about what is being calculated would be really helpful. I'm fine with that being a future ticket

2022-09-19 18:05 UTC, gbggrant commented
So, ran it on a previously run set and it [failed](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/GVS%20AoU%20WGS%2010K%20Callset/job_history/3ec41d9c-046b-4008-9ee6-b2f3a07aec45) as there were rows in the database tables.
Then dropped the tables and it [failed](https://app.terra.bio/#workspaces/allofus-drc-wgs-dev/GVS%20AoU%20WGS%2010K%20Callset/job_history/ce35b598-c634-48fb-9466-a98cfe7b6070) because I dropped the tables. Presumably need a `volatile=true` on the CreateTables task (and make it find or create)?

2022-09-20 16:34 UTC, gbggrant approved these changes

2022-09-21 19:48 UTC, rsasch requested changes
As far as I can tell, this workflow creates the statistics table but does not output the contents into a TSV or CSV, which is what we deliver along with the callset.  Would it be possible to add an export to TSV to a specified GCS location to the CollectStatistics task (or a new one)?

2022-09-21 20:25 UTC, rsasch commented
On the good news front, I compared an export of the "statistics_table" to the callset stats file I generated for Beta and they matched! 👍🏻

2022-09-22 23:23 UTC, mcovarr commented
now with export to CSV

2022-09-23 13:24 UTC, mcovarr commented
Successful run here https://app.terra.bio/#workspaces/gvs-dev/mlc%20GVS%20Quickstart%20v3/job_history/3cacea14-3c61-42ef-9370-2677af5e14d3

2022-09-27 14:15 UTC, rsasch approved these changes

2022-09-27 17:03 UTC, merged