Vs 822 Add documentation for the work that we did on the latest iteration of Delta
broadinstitute/gatk pull request #8205
Opened 2023-02-15 19:30 UTC by RoriCremer

This includes:
* the GQ0 --> no call conversion
* the setting of the max ref block size (already 1000, but need to let the VDS know)

Bonus:
a validation script for the VDS itself

2023-02-21 19:20 UTC, RoriCremer commented on scripts/variantstore/docs/aou/vds/vds_validation.py
> +    hl.init(tmp_dir=f'{temp_path}/hail_tmp_general') ## used by vds.validate()
right--I didn't initially put it at the top because I wanted us to pass the value, but which is better?

2023-02-21 19:21 UTC, RoriCremer commented on scripts/variantstore/docs/aou/vds/vds_validation.py
> +    parser.add_argument('--vds_path', type=str, help='Input VDS Path', default="@VDS_INPUT_PATH@")
hahaha I think I stole one from your code and one from Tim's

2023-02-21 20:10 UTC, RoriCremer commented on scripts/variantstore/docs/aou/vds/vds_validation.py
> +    hl.init(tmp_dir=f'{temp_path}/hail_tmp_general') ## used by vds.validate()
ok perfect--that does feel cleaner

2023-02-21 20:10 UTC, RoriCremer commented on scripts/variantstore/docs/aou/vds/vds_validation.py
> +    hl.init(tmp_dir=f'{temp_path}/hail_tmp_general') ## used by vds.validate()
thank you!

2023-02-21 22:00 UTC, RoriCremer commented on scripts/variantstore/docs/aou/vds/Creating a VDS.md
> +import hail as hl
this isn't where I want this though, is it?

2023-02-22 16:22 UTC, rsasch requested changes

2023-02-22 16:22 UTC, rsasch commented on scripts/variantstore/docs/aou/vds/Creating a VDS.md
> +NOTE: This doc is very much a work in process and is serving as a way to keep track of Hail commands that were used for Delta after the initial VDS delivery
```suggestion
**NOTE:** This doc is very much a work in process and is serving as a way to keep track of Hail commands that were used for Delta after the initial VDS delivery.
```

2023-02-22 16:22 UTC, rsasch commented on scripts/variantstore/docs/aou/vds/Creating a VDS.md
> +
please format as code (surrounded by ```)

2023-02-22 16:22 UTC, rsasch commented on scripts/variantstore/docs/aou/vds/Creating a VDS.md
> +""" Turn the GQ0s into no calls"""
Why the change in formatting? (previous headers were marked with #'s)

2023-02-22 16:22 UTC, rsasch commented on scripts/variantstore/docs/aou/vds/Creating a VDS.md
> +vds2 = hl.vds.VariantDataset(reference_data=rd, variant_data=vds.variant_data)
please format as code

2023-02-22 16:22 UTC, rsasch commented on scripts/variantstore/docs/aou/vds/Creating a VDS.md
> +vds2.write(final_path, overwrite=True)
please format as code

2023-02-22 16:22 UTC, rsasch commented on scripts/variantstore/docs/aou/vds/Creating a VDS.md
> +Run [VDS Validation](vds_validation.py) a python script on the created VDS to ensure that it is ready to be shared
Copy the [VDS Validation](vds_validation.py) python script to the notebook environment with the following arguments:

- `--vds-path`: the GCS path to the newly-created VDS
- `--temp-path`:  a GCS path for temp files to live

```suggestion
Run [VDS Validation](vds_validation.py) a python script on the created VDS to ensure that it is ready to be shared
```

2023-02-22 17:49 UTC, mcovarr commented on scripts/variantstore/docs/aou/vds/Creating a VDS.md
> +import hail as hl
All of our Hail scripts should do a `hail.init(tmp_dir="...")` before invoking any other Hail functions, so this would seem to be the spot for that.

2023-03-13 18:38 UTC, rsasch commented on scripts/variantstore/docs/aou/vds/Creating a VDS.md
> +Copy the [VDS Validation python script](vds_validation.py) to the notebook environment
nit
```suggestion
Copy the [VDS Validation python script](vds_validation.py) to the notebook environment. 
```

2023-03-13 18:39 UTC, rsasch approved these changes
one more nit, otherwise 👍🏻

2023-03-13 19:26 UTC, RoriCremer commented on scripts/variantstore/docs/aou/vds/Creating a VDS.md
> +import hail as hl
can I just set it to this?:
hl.init(tmp_dir='gs://fc-secure-fb908548-fe3c-41d6-adaf-7ac20d541375/temp/')

2023-03-14 15:32 UTC, mcovarr commented on scripts/variantstore/docs/aou/vds/Creating a VDS.md
> +import hail as hl
if that's the workspace bucket I think that should be fine

2023-03-14 15:34 UTC, mcovarr approved these changes
Approved with the inclusion of `hl.init(tmp_dir='gs://blah/...')`

2023-03-14 17:49 UTC, merged