All sample inputs as files instead of strings [VS-1019]
broadinstitute/gatk pull request #8444
Opened 2023-07-31 13:51 UTC by rsasch

Ran into what looks like a limit of the WDL `read_string()`, so converted all the sample-based inputs to be files (instead of strings).

Run that worked (until quotas kicked in): https://app.terra.bio/#workspaces/gvs-dev/GVS_190k_Exomes/job_history/49b92660-e5d6-4305-9857-1dcd19dde1e7

2023-07-31 18:05 UTC, mcovarr approved these changes

2023-07-31 18:17 UTC, rsasch commented on scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
> +        docker: "gcr.io/google.com/cloudsdktool/cloud-sdk:426.0.0-alpine"
Happy to replace it with something else, but this looked like the smallest image that would do the trick and we are already using.  Any suggestions?

2023-07-31 18:18 UTC, mcovarr commented on scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
> +        docker: "gcr.io/google.com/cloudsdktool/cloud-sdk:426.0.0-alpine"
This is fine for now, at some point we should do a pass of upgrading everything but that certainly doesn't have to be in this PR

2023-08-01 14:04 UTC, gbggrant approved these changes
Looks good.

2023-08-01 14:04 UTC, gbggrant commented on scripts/variantstore/wdl/GvsAssignIds.wdl
>        echo "No sample names passed. Exiting"
nit: On first read this sounds like they 'passed', like succe
```suggestion
      echo "No sample names found in file ~{sample_names}. Exiting"
```

2023-08-01 14:16 UTC, rsasch commented on scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
> +        docker: "gcr.io/google.com/cloudsdktool/cloud-sdk:426.0.0-alpine"
slim is 410.5 MB, alpine is 233.4 MB

2023-08-01 15:18 UTC, mcovarr commented on scripts/variantstore/wdl/GvsBulkIngestGenomes.wdl
> +        docker: "gcr.io/google.com/cloudsdktool/cloud-sdk:426.0.0-alpine"
Yeah alpine is preferable if it works for the task at hand

2023-08-01 15:42 UTC, koncheto-broad requested changes
Note: if the changes make the original WDLs unrunnable through normal means, you'll need to document that somewhere.  Up until now, we are still able to run these individual steps to develop on them, debug them, or even push a custom callset through piecemeal.  If this changes our ability to do that, we'll need to document it (or create a ticket to do so).

This is the same feedback given to the PR that joined the output from the early stages of bulk ingest into a single, multi-columned csv.  In that one, Miguel chose to implement it in such a way as to leave the others runnable.

2023-08-01 17:12 UTC, koncheto-broad approved these changes
Thanks for updating the instructions!  I'd prefer if we didn't have to change the inputs this way at all, but this is the most direct way to get around the read_lines() bug at scale

2023-08-01 18:30 UTC, merged