VS-1024 beta workflow for exomes
broadinstitute/gatk pull request #8515
Opened 2023-09-07 17:41 UTC by gbggrant

This PR Creates and exposes the `is_wgs` parameter in the GvsJointVariantCalling wdl.
It follows the rules defined in the ticket VS-1020 as to how to set `is_wgs` and the `optional interval_list` and `interval_weights_bed` inputs

2023-09-07 17:42 UTC, gbggrant commented
Successful Joint Calling workflow (Exome) [here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Exome%20Beta%20Test%20ggrant/job_history/0ff13881-727f-4fdf-bde7-904559eac58f).

2023-09-07 20:33 UTC, gbggrant commented on scripts/variantstore/beta_docs/gvs-exome-workspace-description.md
> +### Genomic Variant Store Exomes workflow (beta) for variant discovery
Note - this document needs further additions / updates probably done by @kbergin

2023-09-08 15:02 UTC, kbergin requested changes

2023-09-08 15:02 UTC, kbergin commented on scripts/variantstore/beta_docs/gvs-exome-workspace-description.md
> +*Our test of 25,000 genomes hit some cloud turbulence and took longer than it should have. As it is an expensive test at this scale, we will update this chart when we have a need to run it again.
just a note that we'll want to remove this line for exomes

2023-09-08 15:02 UTC, kbergin commented on scripts/variantstore/beta_docs/gvs-exome-workspace-description.md
> +### What data does it require as input?
I think this section should mention that it uses xyz interval list for exomes by default, and the linked documentation 'run your own samples' can give a bit more detail about where a readme is about that interval list. I'll update the linked documentation when I do the docs update for exomes.

2023-09-08 19:13 UTC, mcovarr approved these changes

2023-09-11 16:56 UTC, kbergin approved these changes
Thanks for updating that!

2023-09-11 19:32 UTC, merged