Fix population typo [VS-1155]
broadinstitute/gatk pull request #8665
Opened 2024-01-25 14:57 UTC by rsasch

Created VAT here: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/f5abb5af-2f50-4f72-bbd8-e786d49e13be
Validated VAT here: https://app.terra.bio/#workspaces/gvs-dev/RSA%20-%20GVS%20Quickstart%20V2%20/job_history/ee3a7afe-6c4c-4d95-a7ee-83d889d9b289

2024-01-25 21:52 UTC, mcovarr requested changes
I think this is supposed to be changing this to NFE, not NFR

2024-01-25 21:52 UTC, mcovarr commented on scripts/variantstore/variant_annotations_table/GvsValidateVAT.wdl
> +        bq --apilog=false query --nouse_legacy_sql --project_id=~{project_id} --format=csv \
uh how could this have worked before?

2024-01-25 21:52 UTC, mcovarr commented on scripts/variantstore/variant_annotations_table/GvsValidateVAT.wdl
> +        bq --apilog=false query --nouse_legacy_sql --project_id=~{project_id} --format=csv \
same q

2024-01-25 21:52 UTC, mcovarr commented on scripts/variantstore/wdl/extract/extract_subpop.py
> + "nfr",
I thought this was PR was about changing nfr to nfe (or at least that's what the ticket says)

2024-01-25 21:59 UTC, rsasch commented on scripts/variantstore/variant_annotations_table/GvsValidateVAT.wdl
> +        bq --apilog=false query --nouse_legacy_sql --project_id=~{project_id} --format=csv \
dunno, but it was breaking without it

2024-01-26 16:09 UTC, mcovarr approved these changes
code changes look fine but obvs we want to root cause the validation failure

2024-01-29 18:54 UTC, merged