VS-1395 have create vat from vds optionally take sites only vcf echo callset version
broadinstitute/gatk pull request #8866
Opened 2024-06-10 19:42 UTC by gbggrant

* Have GvsCreateVATfromVDS.wdl take sites-only-vcf as an optional input.
* Added logic to allow/disallow CopyFile to overwrite.

[Here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/bb8906d4-7111-4fd1-a723-b5616b354c23) is a passing run using an existing sites-only VCF.
[Here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Quickstart%20v3%20ggrant/job_history/9c8be4d5-f707-4c54-bde5-18d9d23cde66) is a run where it tried to generate the sites-only VCF. Failing because of Echo issues with creating VDS.
[Here](https://app.terra.bio/#workspaces/gvs-dev/GVS%20Integration/job_history/8f8cc493-b0ff-4d8c-8813-6c463dbf17c0) is an integration test. It's failing in ValidateVDS on two paths (the ones that create VDSes) since this is based off of EchoCallset branch - this is expected

2024-06-17 13:15 UTC, rsasch commented on scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
>          vds_path: {
might be useful to add that if `sites_only_vcf` is passed, the WDL will error if `vds_path` is set

2024-06-17 13:15 UTC, rsasch commented on scripts/variantstore/wdl/GvsCreateVATfromVDS.wdl
> +        }
wouldn't it be just as easy to add the trailing slash and not fail?

2024-06-17 14:49 UTC, rsasch requested changes
Have a couple of questions/nits; otherwise looks good

2024-06-20 19:04 UTC, gbggrant commented
@rsasch I've addressed your suggestions. Could you please take another look?

2024-06-20 19:51 UTC, rsasch approved these changes
Thanks!

2024-06-20 20:02 UTC, merged