VS-1466 restructure export vcf for copy reasons
broadinstitute/gatk pull request #8960
Opened 2024-08-22 17:57 UTC by gbggrant

2024-08-26 14:29 UTC, rsasch requested changes
Why is there both a `CreateManifest` and `MakeManifestEntryAndOptionallyCopyOutputs` task?  Why not just have`MakeManifestEntryAndOptionallyCopyOutputs` do the work of both?

2024-08-26 14:29 UTC, rsasch commented on scripts/variantstore/wdl/GvsExtractCallset.wdl
> +
```suggestion
```

2024-08-27 14:44 UTC, rsasch approved these changes
LGTM — thanks for the changes!

2024-08-28 15:57 UTC, mcovarr approved these changes

2024-08-28 19:22 UTC, merged