Port of `CallableLoci` from GATK3
broadinstitute/gatk pull request #9031
Opened 2024-11-02 02:51 UTC by jonn-smith

Ported `CallableLoci` from GATK3 as an experimental tool.

I have not included tests, but have verified on a test file that the statistics and regions are basically identical to the GATK3 results.

2024-11-05 20:00 UTC, lbergelson requested changes
@jonn-smith I have some comments.  I noticed a few things that are minor bugs around the inputs, and then there are some style things I would probably change.

2024-11-05 20:03 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +    private byte maxLowMAPQ = 1;
👍

2024-11-05 20:05 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +    private byte minBaseQuality = 20;
👍

2024-11-05 20:05 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +    private int minDepth = 4;
👍

2024-11-05 20:07 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +    public enum CalledState {
👍

2024-11-05 20:18 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +    protected static class CallableBaseState {
👍

2024-11-05 20:48 UTC, cmnbroad commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> + *     -T CallableLoci \
Drive by nit: this is GATK3 CLI syntax.

2024-11-05 20:55 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +        private SimpleInterval interval;
👍

2024-11-05 20:55 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +        public CallableBaseState(SimpleInterval interval, CalledState state) {
👍

2024-11-05 20:56 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +        public SimpleInterval getLocation() {
👍

2024-11-05 20:57 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +        public boolean changingState(CalledState newState) {
👍

2024-11-05 20:58 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +        public void update(SimpleInterval newInterval) {
👍

2024-11-05 20:59 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +        public String toString() {
👍

2024-11-05 21:01 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +    private File outputFile = null;
👍

2024-11-05 21:05 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +        if (getHeaderForReads().getReadGroups().stream()
👍

2024-11-05 21:08 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +        if (BaseUtils.isNBase(referenceContext.getBase())) {
👍

2024-11-05 21:09 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +            outputStream.println(callableState.toString());
👍

2024-11-05 21:10 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +    private PrintStream outputStream = null;
👍

2024-11-05 21:12 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +        outputStream.close();
👍

2024-11-05 21:12 UTC, jonn-smith commented on src/test/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLociIntegrationTest.java
> +    public static final String testDataDir = largeFileTestDir + "/org/broadinstitute/hellbender/tools/walkers/coverage/callableloci/";
👍

2024-11-05 21:14 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> + *     -T CallableLoci \
👍

2024-11-05 21:51 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +    private static double ratio(int numerator, int denominator) {
Yeah - it was a hold-over from the old implementation.

I'll remove it.

2024-11-05 22:00 UTC, jonn-smith commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +    private Integrator integrator;
👍

2024-11-05 22:01 UTC, jonn-smith commented
@lbergelson @cmnbroad Thanks for the comments.  This was an interesting first experiment in using LLM-assisted coding.  Looks like it doesn't understand our codebase quite as well as I would like, though it did produce working code.  I'll see if I can tweak things in the future.

In the meantime, back to you @lbergelson for another round if you like.

2024-11-08 20:50 UTC, lbergelson commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> + * <dd>More than --max-depth read at the locus, indicating some sort of mapping problem</dd>
good catch, I didn't see these.

2024-11-08 20:51 UTC, lbergelson commented on src/main/java/org/broadinstitute/hellbender/tools/walkers/coverage/CallableLoci.java
> +    private static class StateCounter {
👍 I know it's a few more lines but I think it's much clearer.

2024-11-08 20:52 UTC, lbergelson approved these changes
@jonn-smith Thanks for making the changes.  I know they were kind of nitpicky but I think its better this way.

2024-11-08 20:54 UTC, merged